// <auto-generated />
using InventorySystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventorySystem.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnName("is_discontinued")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            IsDiscontinued = false,
                            Name = "Renberget",
                            Quantity = 5
                        },
                        new
                        {
                            ID = -2,
                            IsDiscontinued = false,
                            Name = "Loberget",
                            Quantity = 0
                        },
                        new
                        {
                            ID = -3,
                            IsDiscontinued = true,
                            Name = "Loberget",
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
